server.port:8081
spring.application.name=market-data-service

spring.datasource.url=jdbc:postgresql://localhost:5432/marketdata_db
spring.datasource.username=marketdata_user
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=false
spring.jpa.hibernate.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization= true
spring.sql.init.mode=always



