
server.port:8080
spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5432/marketdata_db
spring.datasource.username=marketdata_user
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.hibernate.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization= true
spring.sql.init.mode=always

app.jwt.secret=mySecretKey123456789012345678901234567890
app.jwt.expiration=86400

app.market-data-service.url=http://localhost:8081
app.market-data-service.timeout=3000




